CREATE TABLE zlodziej (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    usr VARCHAR2(30),
    czas_zmiany DATE
);

CREATE OR REPLACE TRIGGER trg_check_salary_range
BEFORE INSERT OR UPDATE ON employees
FOR EACH ROW
BEGIN
    IF :NEW.salary < 2000 OR :NEW.salary > 26000 THEN
        INSERT INTO zlodziej (usr, czas_zmiany) VALUES (USER, SYSDATE);
        RAISE_APPLICATION_ERROR(-20020, 'Zarobki poza dozwolonym zakresem (2000 - 26000). Operacja zabroniona.');
    END IF;
END;