CREATE OR REPLACE TRIGGER trg_no_dml_job_grades
BEFORE INSERT OR UPDATE OR DELETE ON job_grades
BEGIN
    RAISE_APPLICATION_ERROR(-20030, 'Operacje INSERT, UPDATE i DELETE są zabronione na JOB_GRADES.');
END;